import '../../../my_custom_widget.dart';
import '../../constants/constants.dart';

final Map<String, String> ar = {
  "title": "${MozaicLoyaltySDK.settings.appTitleAr}",
  "forceUpdate": "يرجى تحديث التطبيق للمتابعة!",
  "update": "تحديث",
  'pleaseEnterYourMobileNumber': "أدخل رقم هاتفك للبدء",
  "mobileNumber": "رقم الهاتف",
  "isReq": "مطلوب",
  'activationDate': 'تاريخ التفعيل',
  "wrongMobile": "رقم الهاتف لا يجب ان يقل عن 9 أرقام",
  "wrongMobile?": "أدخلت رقم هاتف خاطئ؟",
  "numberShouldStart5": "يجب ان يبدأ الرقم ${AppConstants.countryCodeStart} أو ${AppConstants.countryCodeStartWithZero}",
  "next": "التالي",
  "skip": "تخطى",
  "acceptTermsPrivacy": "إنشاء حسابك يعني أنك قد وافقت على",
  "termsCondition": "الشروط والأحكام ",
  "privacyPolicy": "سياسة الخصوصية ",
  "and": "و",
  "edit": "تعديل",
  'pleaseAgreeTermsAlert': 'يرجى الموافقة على الشروط والأحكام',
  "verification": "تفعيل الحساب",
  'verificationDes': 'لقد قمنا بإرسال رمز التفعيل لرقم هاتفك',
  "pasteCode": "لصق الرمز",
  "paste": "لصق",
  "confirmPaste": "هل أنت متأكد من أنك تريد لصق الرمز:",
  "letsGo": "تفعيل",
  "resendOtp": "إعادة ارسال (SMS)",
  "needHelp": "تحتاج مساعدة؟ تواصل معنا",
  'changeMobile': 'هل تريد تغيير رقم الهاتف',
  'completeProfile': 'قم بإكمال بيانات حسابك',
  "fName": "الاسم الأول",
  "lName": "الاسم الأخير",
  "bod": "تاريخ الميلاد",
  "gender": "الجنس",
  "maritalStatus": "الحالة الاجتماعية",
  "firstNameLengthMustMoreThan3Char": "يجب أن يكون طول الاسم الأول أكثر من 3 أحرف",
  "lastNameLengthMustMoreThan3Char": "يجب أن يكون طول الاسم الأخير أكثر من 3 أحرف",
  "male": "ذكر",
  "female": "أنثى",
  "married": "متزوج",
  "single": "أعزب",
  "save": "حفظ",
  "optional": "اختياري",
  "selectYourGender": "اختر الجنس",
  "referralCode": "رمز الدعوة",
  "selectYourBirthdate": "اختر تاريخ الميلاد",
  "selectAnniversaryDate": "اختر تاريخ الزواج",
  "selectYourCity": "اختر مدينتك",
  "city": "المدينة",
  "area": "المنطقة",
  "anniversaryDate": "تاريخ الزواج",
  "selectArea": "اختر المنطقة",
  "selectYourMaritalStatus": "اختر الحالة الاجتماعية",
  "referralCodeError": "يرجى ادخال رمز الدعوة",
  "enterReferralCode": "أدخل رمز الدعوة",
  "referralCodeTxt": "هل تلقيت دعوة من صديق؟ أضف الرمز أدناه لتأكيد الدعوة",
  "citiesListEmpty": "القائمة فارغة",
  'homeTab': 'الرئيسية',
  'branches': 'فروعنا',
  'checkIn': 'أنا هنا',
  "Welcome": "مرحباً",
  'profile': 'حسابي',
  'orderHistory': 'طلباتي',
  'inviteFriends': 'دعوة صديق',
  'contactUs': 'اتصل بنا',
  'connectWithUs': 'تفاعل معنا',
  'rateOurApp': 'قيم التطبيق',
  'Language': 'اللغة',
  'developedBy': 'مطور التطبيق',
  'nightMode': 'الوضع الليلي',
  'myAddresses': 'عناويني',
  "deleteAccount": "حذف الحساب",
  "confirmDelete": "سيؤدي حذف حسابك إلى حذف جميع النقاط والمكافآت ولا يمكن استعادتها.",
  "editProfile": "تعديل بيانات حسابي",
  'inviteTxt': 'قم بمشاركة تطبيق ${MozaicLoyaltySDK.settings.appTitleAr} مع أصدقائك',
  'invite': 'دعوة',
  "connectWithUsOnSocialMedia": "ﺗﺎﺑﻌﻨﺎ ﻋﲆ ﻣﻨﺼﺎت اﻟﺘﻮاﺻﻞ اﻹﺟﺘﻤﺎﻋﻲ",
  "visitOurWebsite": "أو ﻗﻢ ﺑﺰﻳﺎرة ﻣﻮﻗﻌﻨﺎ اإﻟﻜﱰوﱐ",
  'readAll': 'تعيين كمقروء',
  "emptyBranches": "لا يوجد حاليا أي فروع متاحة.",
  'workingHour': 'ساعات العمل',
  "callUs": "اتصل بنا",
  'location': "الموقع",
  "exitApp": "الخروج من التطبيق",
  "confirmExitApp": "هل أنت متأكد من الخروج من التطبيق",
  'pleaseWait': 'يرجى الإنتظار',
  "checkInComplete": "شكرا لزيارتكم فرعنا",
  "checkInNotComplete": "يرجى زيارة أقرب فرع لدينا",
  'done': 'موافق',
  "myPoints": "نقاطي",
  "noHistory": 'لا يوجد سجلات',
  'redeemed': 'نقاط مستبدلة',
  'expired': 'نقاط منتهية',
  'visits': 'زياراتي',
  "creationDate": "تاريخ العملية",
  "TransactionType": "نوع العملية",
  "expiryDate": "تاريخ الانتهاء",
  "branchName": "اسم الفرع",
  'validUntil': 'صالحة لغاية',
  "valid": "متاحة",
  'rewards': 'المكافآت',
  "email": "بريدك الإلكتروني",
  "enterEmail": "يرجى إدخال بريدك الإلكتروني",
  "invalidEmail": "يرجى إدخال بريد إلكتروني صالح",
  "note": "الملاحظات على الطلب",
  "pleaseEnterNote": "يرجى إدخال رسالتك",
  'orContactUsVia': 'أو اتصل بنا عبر',
  "send": 'أرسل',
  "notificationEmpty": "لا يوجد تنبيهات، ترقب الإشعارات!",
  "somethingWrong": "حدث خطأ ما",
  'scanToCollectPoints': 'امسح الرمز لجمع النقاط!',
  "menu": "القائمة",
  "noInternet": "لا يوجد اتصال بشبكة الانترنت",
  "jd": "د.أ",
  "sar": "ر.س",
  'rewardsGallery': 'معرض المكافآت',
  "points": "النقاط",
  'quantity': 'الكميه',
  'redeemGift': 'استبدل الهدية',
  'redeemMultiConfirm': 'هل أنت متأكد من أنك تريد استرداد',
  'for': 'مقابل',
  'enjoyGifting': 'استمتع بهديتك ، قم بزيارة أي من فروعنا للحصول على الهدية.',
  'congratulations': 'تهانينا!',
  "cancel": "إلغاء",
  "confirm": "موافق",
  "loading": "تحميل",
  'youDoNotHaveBalance': 'لا يوجد لديك رصيد كاف لاستبدال هذه الهدية',
  "notifications": "إشعارات",
  "searchBranch": "ابحث عن الفرع",
  'addNewAddress': 'أضف عنوان جديد',
  'selectYourAddress': 'اختر عنوانك',
  'addressDetails': 'تفاصيل العنوان (المنطقة، الشارع)',
  'home': 'المنزل',
  'work': 'العمل',
  'other': 'أخرى',
  'buildingNum': 'رقم البناية (١٢أ، ٩٦ب، إلخ)',
  'addressLabelList': ' (المنزل، العمل، الخ)',
  'floorNum': 'رقم الطابق',
  'addressLabel': ' اسم العنوان (المنزل، العمل، الخ)',
  'noSavedAddresses': 'لا يوجد أماكن محفوظة',
  'deleteAddress': "حذف العنوان",
  "thisWillDelete": "سيتم حذف",
  "fromYourSavedAddresses": "من العنوان المحفوظ لديك",
  "enter": "أدخل",
  "chooseDeliveryLocation": "اختر موقع التسليم",
  "savedAddresses": "العناوين المحفوظة",
  'addToCart': 'إضافة الى السلة',
  'pleaseSelectFrom': 'يرجى الاختيار من',
  "cart": "سلة المشتريات",
  "paymentMethod": "طريقة الدفع",
  "orderMethod": "طريقة الطلب",
  "orderSummary": "ملخص الطلب",
  "callMeToConfirm": "لا تتصل بي لتأكيد الطلب.",
  "subTotal": "المجموع الفرعي",
  "deliveryFee": "رسوم التوصيل",
  "taxDesc": "شكرًا لتسوقك معنا.",
  "finalAmount": "المبلغ النهائي",
  'selectPaymentMethod': 'الرجاء اختيار طريقة الدفع',
  'cancelCartBody': 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟',
  'cancelOrder': 'إلغاء الطلب',
  'tax': 'ضريبة المبيعات',
  'orderReceived': 'تم استلام الطلب',
  'orderText': ' شكرا لطلبك من${MozaicLoyaltySDK.settings.appTitleAr}',
  'orderId': 'رقم الطلب',
  'orderDate': 'تاريخ الطلب',
  'viewOrder': 'عرض الطلب',
  'orderStatus': 'حالة الطلب',
  'status': 'الحالة',
  'ourBranches': 'فروعنا',
  'pendingForPayment': 'بإنتظار الدفع',
  'approved': 'تم قبول الطلب',
  'inProgress': 'الطلب قيد التنفيذ',
  'onItsWay': 'الطلب في الطريق',
  'orderIsCanceled': 'تم إلغاء الطلب',
  'orderComplete': 'تم إتمام الطلب',
  'unknown': 'غير معرف',
  'deliveryDate': 'تاريخ التسليم',
  'pickUpDate': 'تاريخ الأستلام',
  'callStore': 'إتصل بالمتجر',
  'showInMap': 'عرض على الخريطة',
  'deliveryAddress': 'عنوان التوصيل',
  'totalPrice': 'إجمالي السعر',
  'oneItemPrice': 'السعر عدد(1) ',
  'deliveryDiscount': "خصم التوصيل",
  'orderDiscount': 'خصم الطلب',
  'callYou': ' سيتواصل معكم مركز اتصال شركة ${MozaicLoyaltySDK.settings.appTitleAr} لتأكيد تفاصيل طلبكم وتزويدكم بمعلومات حول رسوم التوصيل. ',
  'selectPaymentMethodFirst': 'اختر طريقة الدفع',
  'address': 'العنوان',
  'subTotalFromTo': 'يجب أن يكون مبلغ الطلب ضمن:',
  "minimumSubTotal": "الحد الأدنى للمبلغ الإجمالي الفرعي هو",
  "MinimumOrder": "الحد الأدنى للطلب",
  "Type": "النوع",
  "Percentage": "نسبة مئوية",
  "Amount": "مبلغ",
  "Value": "القيمة",
  "range": "نطاق المجموع الفرعي",
  "noItems": "لا يوجد منتجات",
  "pleaseLogin": 'الرجاء التسجيل حتى تتمكن من إستخدام جميع المزايا',
  'noOrders': 'لا يوجد طلبات',
  'orderNow': 'أطلب الآن',
  'noInternetBody': 'يرجى التحقق من الاتصال بالإنترنت',
  "refresh": "تحديث",
  'limitationTex': 'عذراً, لا يمكن إضافة هذا المنتج الى سلة المشتريات.\n\nالحد الأعلى للطلب الواحد من منتجات القهوة\n',
  'Unavailable': "غير متاح",
  "Available": "متاح",
  'watchOnYoutube': 'شاهد على اليوتيوب',
  'IsActivePerBranch': "نأسف لإعلامكم بأن هذا المنتج غير متوفر في ",
  "selectSize": "اختر الحجم",
  "pleaseSelectSize": "الرجاء اختيار الحجم",
  "discount": "الخصم",
  "ClearCartBody": "عند اختيار عنوان جديد او تغيير طريقة الاستلام سيتم افراغ سلة مشترياتك.",
  "ClearCartTitle": "بدء سلة جديدة؟",
  'orderFailed': 'فشل الدفع',
  'orderPending': 'بانتظار تأكيد الدفع',
  'paymentPendingMessage': 'يرجى الانتظار حتى للتأكد من نجاح عملية الدفع',
  'paymentFailedMessage': 'لم تتم المعاملة بنجاح. يُرجى المحاولة مرة أخرى',
  'orderCanceled': 'تم إلغاء الطلب',
  'orderCanceledMessage': 'تم إلغاء طلبك.',
  "pointSchema": "فوائد العضوية",
  "delete": "حذف",
  "logOut": "تسجيل الخروج",
  "confirmLogout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "fullName": "الاسم الكامل",
  "loyaltyTransactions": "سجل النقاط",
  "emptyPoints": "سجل نقاطك فارغ؟ ابدأ الكسب!",
  "emptyRewards": "لا مكافآت بعدا!",
  "emptyBrands": "قائمة العلامات التجارية فارغة حاليا.",
  "emptyList": "لا توجد بيانات حاليا في القائمة.",
  "tierInfoTitle": "اكتشف مزايا العضوية",
  "tierInfoDesc": "اضغط هنا لاستكشاف المزايا الحصرية للعضوية والتعرف على جميع الفئات في جميع فروعنا.",
  "redeem": "الاستبدال",
  "myRewards": "مكافآتي",
  "moreRewards": "المكافآت المستقبلية",
  "discoverNow": "اكتشف الآن",
  "redeemReward": "استرداد المكافأة",
  "tier": "المستوى",
  "balance": "الرصيد",
  "aboutUs": "معلومات عنا",
  "brandName": "العلامة التجارية",
  "from": "من",
  "to": "الى",
  "above": "أكثر من",
  'GoodMorning': 'صباح الخير',
  'GoodAfternoon': 'مساء الخير',
  'GoodEvening': 'مساء النور',
  "selectAddressFirst": "اختر عنوان التوصيل",
  "deliverTo": "توصيل الى",
  "redeemPointsForThisOrder": "استبدال النقاط لهذا الطلب",
  "redeemPoints": "إستبدل نقاطك",
  "PendingForPayment": "في انتظار الدفع",
  "PendingForReview": "في انتظار المراجعة",
  "PendingForApprove": "في انتظار الموافقة",
  "InProgress": "قيد التنفيذ",
  "ReadyForDelivery": "جاهز للتسليم",
  "Canceled": "ملغي",
  "Closed": "مغلق",
  'close': 'إغلاق',
  'scanQR': 'قم بمسح الكود لأستبدال النقاط.',
  'developer': 'المطور',
  "ReadyForPickup": "جاهز للاستلام",
  'missions': 'المهام',
  'pickUp': 'استلام',
  "rateYourExperienceWithUs": "قيم تجربتك معنا",
  "leaveAFeedback": "اترك تعليقا",
  "notEnrolled": "مرحبًا! يرجى التسجيل لبدء رحلتك معنا واكتشاف جميع الميزات الرائعة التي نقدمها.",
  "wantToCall": "هل تريد الاتصال بنا؟",
  "login": "تسجيل الدخول",
  "changeLanguage": "تغيير اللغة",
  "confirmChangeLanguage": "التحويل إلى اللغة الإنجليزية؟",
  "verificationSent": "تم إرسال رمز التحقق إلى رقم هاتفك",
  "enter4Digit": "أدخل الرمز المكون من 4 خانات",
  "visitorType": "نوع الزائر",
  "selectYourVisitorType": "حقل اجباري",
  'spend': 'اصرف',
  "toStayIn": "للمحافظة على",
  "toReach": "للوصول الى",
  "seeMore": "عرض المزيد",
  "whatsNew": "ما الجديد",
  "offers": "العروض",
  "thanksForRating": "شكرا لتقييمك لنا",
  "expiry": "المنتهية",
  "outOfStock": "إنتهى من المخزن",
  "filter": "فلترة",
  "clearAll": "حذف الكل",
  "MaxQuantity": "أقصى كمية متاحة",
  "apply": "تطبيق",
  "enterValue": "ادخل قيمة",
  "youWillPayByCard": "ستدفع بواسطة البطاقة",
  "youWillPayInCash": "ستدفع نقداً",
  "youWillPayFromWallet": "ستدفع من المحفظة",
  "useWallet": "استخدم المحفظة",
  "wallet": "المحفظة",
  "payNow": "ادفع الآن",
  "walletHistory": "سجل المحفظة",
  "getStartedNow": "أهلاً بك في أرابيكا",
  "didntReceiveCode": "لم يصلك رمز التحقق؟",
  "qrCode": "كود QR",
  "pointsBalance": "رصيد النقاط",
  "walletBalance": "رصيد المحفظة",
  "Deals": "عروض",
  "price": "السعر",
  "value": "القيمة",
  "topUpSuccessful": "تمت عملية الشحن بنجاح",
  "topUpSuccessfulSubText": "استمتع بكل رشفة بقيمة إضافية",
  "copiedToClipboard": "تم نسخها إلى الحافظة",
  "pickUpFrom": "إستلام من فرع",
  "noBranchSelected": "لم يتم تحديد أي فرع",
  "select": "اختر",
  "change": "تغيير",
  "notAvailable": "غير متوفر",
  "confirmRemoveItemName": "هل أنت متأكد أنك تريد حذف item@ من سلة التسوق؟",
  "OnBoardingTitle1": "ابقَ على اطلاع بمشروباتك المفضلة",
  "OnBoardingDescription1": "احصل على إشعارات بأحدث المشروبات والعروض الحصرية من المقاهي المصممة خصيصاً لك.",
  "OnBoardingTitle2": "انطلق في رحلة نكهات مع كل فنجان",
  "OnBoardingDescription2": "استكشف عالم القهوة بعمق مع اختيارات مميزة وملاحظات تذوق مختارة بعناية.",
  "OnBoardingTitle3": "أنشئ قائمة قهوتك المفضلة",
  "OnBoardingDescription3": "كوّن مجموعة من مقاهيِك المفضلة لتكون لحظات القهوة المثالية دائماً بالقرب منك.",
  "showOptions": "سعر حسب الاختيار",
  "Refer&Win": "أحِلْ واربح",
  "referAndWinDescription": "شارك قهوة أرابيكا مع أصدقائك واربح مكافآت",
  "topUp": "إشحن حسابك",
  "permissionNotAllowed": "لا يوجد إذن للوصول الى الموقع",
  "locationPermissionShouldAllowed": "هل أعطيت إذن للتطبيق بالوصول للموقع في جميع الاوقات؟",
  "openAppSettings": "فتح اعدادات التطبيق",
  "redeemYourPoints": "استبدل نقاطك",
};
