import '../../../my_custom_widget.dart';
import '../../constants/constants.dart';

final Map<String, String> en = {
  "title": "${MozaicLoyaltySDK.settings.appTitleEn}",
  "forceUpdate": "Update the app to continue!",
  "update": "Update",
  'pleaseEnterYourMobileNumber': "Enter your mobile number to begin",
  "mobileNumber": "Mobile Number",
  "isReq": "Required",
  "wrongMobile": "Mobile number shouldn\'t be less than 9 numbers",
  "wrongMobile?": "Entered the wrong number?",
  "numberShouldStart5": "The number must start with ${AppConstants.countryCodeStart} or ${AppConstants.countryCodeStartWithZero}",
  "next": "Next",
  "skip": "Skip",
  "acceptTermsPrivacy": "By registering,you agree to ${MozaicLoyaltySDK.settings.appTitleEn}",
  "termsCondition": "Terms and Conditions",
  "privacyPolicy": "Privacy Policy ",
  "and": "and",
  "edit": "Edit",
  'pleaseAgreeTermsAlert': 'Please accept Terms & Conditions',
  "verification": "Verification",
  "verificationDes": 'Please enter the verification code sent to your mobile number',
  "pasteCode": "Paste Code",
  "paste": "Paste",
  "confirmPaste": "Are you sure to paste code:",
  "letsGo": "Lets Go !!",
  "resendOtp": "Resend (SMS)",
  "needHelp": "Need help? Contact us",
  'changeMobile': 'Would you like to change your mobile number?',
  'completeProfile': 'Complete Your Profile',
  "fName": "First Name",
  "lName": "Last Name",
  "bod": "Date of Birth",
  "gender": "Gender",
  "maritalStatus": "Marital Status",
  "firstNameLengthMustMoreThan3Char": "The first name must contain at least 3 characters",
  "lastNameLengthMustMoreThan3Char": "The last name must contain at least 3 characters",
  "male": "Male",
  "female": "Female",
  "married": "Married",
  "single": "Single",
  "save": "Save",
  "optional": "Optional",
  "referralCode": "Referral Code",
  "selectYourGender": "Select your gender",
  "selectYourBirthdate": "Select your date of birth",
  "selectYourMaritalStatus": "Select your marital status",
  "referralCodeError": "Enter the referral code",
  "enterReferralCode": "Enter the referral code",
  'referralCodeTxt': 'Did you receive an invitation from a friend? Add the code below to confirm',
  "selectYourCity": "Select your city",
  "city": "City",
  "area": "Area",
  "selectArea": "Select area",
  "selectAnniversaryDate": "Select anniversary date",
  "anniversaryDate": "Anniversary Date",
  "citiesListEmpty": "List is empty",
  'homeTab': 'Home',
  'branches': 'Branches',
  'checkIn': 'Check In',
  "Welcome": "Welcome",
  'profile': 'My Profile',
  'orderHistory': 'My Orders',
  'inviteFriends': 'Invite Friends',
  'readAll': 'Read All',
  'contactUs': 'Contact Us',
  'connectWithUs': 'Connect With Us',
  'rateOurApp': 'Rate Our App',
  'Language': 'Language',
  'developedBy': 'Application Developer',
  'nightMode': 'Night Mode',
  'developer': 'Developer',
  'myAddresses': 'My Addresses',
  "deleteAccount": "Delete Account",
  "confirmDelete": "Deleting your account will delete all points and rewards and it can't be recovered.",
  "editProfile": "Edit Your Profile",
  'inviteTxt': 'Invite your friends to download ${MozaicLoyaltySDK.settings.appTitleEn} App',
  'invite': 'Invite',
  "connectWithUsOnSocialMedia": "Connect with us on social media",
  "visitOurWebsite": "Visit our website",
  "emptyBranches": "There are currently no branches available.",
  'workingHour': 'Working Hours',
  'location': "Location",
  "callUs": " Call us",
  "exitApp": "Exit App",
  "confirmExitApp": "Are you sure you want to exit?",
  'pleaseWait': 'Please wait',
  "checkInComplete": "Thank you For visiting our Branch",
  "checkInNotComplete": "Please visit our nearest branch",
  "done": "Done",
  "myPoints": "My Points",
  "noHistory": 'No History',
  'redeemed': 'Redeemed',
  'expired': 'Expired',
  'visits': 'My Visits',
  "creationDate": "Transaction Date",
  "TransactionType": "Transaction Type",
  "expiryDate": "Expiry Date",
  "branchName": "Branch Name",
  'validUntil': 'Valid until',
  "valid": "Valid",
  "email": 'Your Email',
  "enterEmail": "Please enter your email",
  "invalidEmail": "please enter a valid email",
  "note": "Notes on Order",
  "pleaseEnterNote": "Please enter your message",
  "send": "Send",
  'orContactUsVia': 'Or contact us via',
  "notificationEmpty": "Nothing new? Stay tuned!",
  "somethingWrong": "Something Went Wrong",
  'scanToCollectPoints': 'Scan to collect points',
  "menu": "Menu",
  "noInternet": "No Internet Connection",
  'noInternetBody': 'Please check your internet connection',
  "jd": "JD",
  "sar": "SAR",
  'rewardsGallery': 'Rewards Gallery',
  "points": "Points",
  'quantity': 'Quantity',
  'redeemGift': 'Redeem Gift',
  'redeemMultiConfirm': 'Are you sure you want to redeem',
  "for": "for",
  'congratulations': 'Congratulations!',
  'enjoyGifting': 'Enjoy your gift, visit any of our branches to redeem it.',
  "cancel": "Cancel",
  "loading": "Loading",
  "confirm": "Confirm",
  'youDoNotHaveBalance': 'You do not have enough balance to redeem this gift',
  "notifications": "Notifications",
  "searchBranch": "Search for Branch",
  'addNewAddress': 'Add New Address',
  'selectYourAddress': 'Confirm Your Address',
  'addressDetails': 'Detailed Address (Area, St.name)',
  'home': 'Home',
  'work': 'Work',
  'other': 'Other',
  'buildingNum': 'Building Number (19A, 96B, etc)',
  'addressLabelList': ' (Home, Work, etc)',
  'floorNum': 'Floor Number',
  'addressLabel': 'Address Label (Home, Work, etc)',
  'noSavedAddresses': 'No Saved Addresses',
  'deleteAddress': "Delete Address",
  "thisWillDelete": "This will delete",
  "fromYourSavedAddresses": "from your saved addresses",
  "enter": "Enter",
  "chooseDeliveryLocation": "Choose delivery location",
  "savedAddresses": "Saved Addresses",
  'addToCart': 'Add To Cart',
  'pleaseSelectFrom': 'Please Select From',
  'cart': 'My Cart',
  "paymentMethod": "Payment Method",
  "orderMethod": "Order Method",
  "orderSummary": "Order Summary",
  'callMeToConfirm': 'Don\'t Call me to confirm order.',
  'subTotal': 'Subtotal',
  'deliveryFee': 'Delivery Fee',
  'taxDesc': 'Thank you for shopping with us.',
  'finalAmount': 'Final Amount',
  'selectPaymentMethod': 'Please select a payment method',
  'cancelCartBody': 'Are you sure you want to cancel this order?',
  'cancelOrder': 'Cancel Order',
  'tax': 'Tax',
  'orderReceived': 'Order Received',
  'orderText': 'Thank you for your order',
  'orderId': 'Order ID',
  'orderDate': 'Order Date',
  'orderStatus': 'Order Status',
  'pendingForPayment': 'Pending For Payment',
  'approved': 'Order Approved',
  'inProgress': 'Order In Progress',
  'onItsWay': 'Order On Its Way',
  'orderIsCanceled': 'Order is Canceled',
  'orderComplete': 'Order Completed',
  'unknown': 'Unknown',
  'viewOrder': 'View Order',
  'deliveryDate': 'Delivery Date',
  'pickUpDate': 'Pick Up Date',
  'callStore': 'Call Store',
  'showInMap': 'Show On Map',
  'deliveryAddress': 'Delivery Address',
  'totalPrice': 'Total Price',
  'oneItemPrice': 'Price Quantity(1)',
  'deliveryDiscount': "Delivery Discount",
  'orderDiscount': 'Order Discount',
  'callYou': 'Al Ameed Call Center will reach out to confirm your order details and provide information about the delivery fees.',
  'selectPaymentMethodFirst': 'Select Payment Method',
  'address': 'Address',
  "subTotalFromTo": "Order amount must be within:",
  "minimumSubTotal": "Minimum Subtotal amount is",
  "MinimumOrder": "Minimum Order",
  "Type": "Type",
  "Percentage": "Percentage",
  "Amount": "Amount",
  "Value": "Value",
  "range": "Sub Total Range",
  "noItems": "No Items",
  "pleaseLogin": "Please register to be able to use all application features",
  'noOrders': 'No Orders',
  'orderNow': 'Order Now',
  "refresh": "Refresh",
  'limitationTex': 'Sorry, You can\'t add this item to your basket.\n\n Maximum order amount for coffee items is ',
  'Unavailable': "Unavailable",
  "Available": "Available",
  'watchOnYoutube': 'Watch on Youtube',
  'IsActivePerBranch': "We regret to inform you that this item is not available at ",
  "selectSize": "Select a Size",
  "pleaseSelectSize": "Please select a size",
  "discount": "Discount",
  "ClearCartTitle": "Start a new cart?",
  "ClearCartBody": "Choosing a new address or changing delivery method will clear items in your cart.",
  'orderFailed': 'Payment Failed',
  'orderPending': 'Pending for Payment',
  'paymentPendingMessage': 'Please wait for your payment to be success.',
  'paymentFailedMessage': 'Transaction was not completed successfully. Please try again.',
  'orderCanceled': 'Order Canceled',
  'orderCanceledMessage': 'Your order has been canceled.',
  "pointSchema": 'Membership Benefits',
  "delete": "Delete",
  "logOut": "Logout",
  "confirmLogout": "Are you sure you want to log out?",
  "fullName": "Full Name",
  "loyaltyTransactions": "Points Transactions",
  "emptyPoints": "History empty, start earning!",
  "emptyRewards": "No rewards yet!",
  "emptyBrands": "There are no brands available at this time.",
  "emptyList": "There is currently no data in the list.",
  "tierInfoTitle": "Discover Membership Benefits",
  "tierInfoDesc": "Click here to explore the exclusive membership benefits and learn about all tiers across our branches.",
  "redeem": "Redeem",
  "myRewards": "My Rewards",
  "rewards": "Rewards",
  "moreRewards": "More Rewards",
  "discoverNow": "Discover Now",
  "redeemReward": "Redeem Reward",
  "tier": "Level",
  "aboutUs": "About Us",
  "balance": "Balance",
  "brandName": "Brand Name",
  "from": "From",
  "to": "to",
  "above": "Above",
  'GoodMorning': 'Good Morning',
  'GoodAfternoon': 'Good Afternoon',
  'GoodEvening': 'Good Evening',
  "selectAddressFirst": "Select your delivery address",
  "deliverTo": "Deliver to",
  "redeemPointsForThisOrder": "Redeem points for this order",
  "redeemPoints": "Redeem points",
  "PendingForPayment": "Pending For Payment",
  "PendingForReview": "Pending For Review",
  "PendingForApprove": "Pending For Approve",
  "InProgress": "In Progress",
  'missions': 'Missions',
  "ReadyForDelivery": "Ready For Delivery",
  "Canceled": "Canceled",
  "Closed": "Closed",
  "ReadyForPickup": "Ready For Pickup",
  'pickUp': 'Pick Up',
  "rateYourExperienceWithUs": "Rate your experience with us",
  "leaveAFeedback": "Leave a feedback",
  "notEnrolled": "Welcome! Please sign up to start your journey with us and unlock all the exciting features.",
  "wantToCall": "Do you want to call us?",
  "login": "Login",
  "changeLanguage": "Change Language",
  "confirmChangeLanguage": " switching to Arabic language?",
  "verificationSent": "A verification code has been sent to your mobile",
  "enter4Digit": "Enter 4-digits code",
  "visitorType": "Visitor Type",
  "selectYourVisitorType": "This Field is Required",
  "spend": "Spend",
  "toStayIn": "to stay in",
  "toReach": "to reach",
  "seeMore": "See more",
  "whatsNew": "What's New",
  "offers": "Offers",
  "thanksForRating": "Thanks for rating us",
  "expiry": "Expiry",
  "outOfStock": "Out of Stock",
  "filter": "Filter",
  "clearAll": "Clear All",
  "MaxQuantity": "is the maximum quantity available",
  "apply": "Apply",
  "enterValue": "Enter Value",
  "close": "Close",
  "ourBranches": "Our Branches",
  "status": "Status",
  "activationDate": "Activation Date",
  "brands": "Brands",
  "scanQR": "Scan code to collect points.",
  "youWillPayByCard": "You will pay by card",
  "youWillPayInCash": "You will pay in cash",
  "youWillPayFromWallet": "You will pay from wallet",
  "useWallet": "Use Wallet",
  "wallet": "Wallet",
  "payNow": "Pay Now",
  "walletHistory": "Wallet Transactions",
  "qrCode": "QR-Code",
  "pointsBalance": "Points Balance",
  "walletBalance": "Wallet Balance",
  "getStartedNow": "Welcome to ${MozaicLoyaltySDK.settings.appTitleEn}",
  "Deals": "Deals",
  "price": "Price",
  "value": "Value",
  "Refer&Win": "Refer & Win",
  "referAndWinDescription": "Share ${MozaicLoyaltySDK.settings.appTitleEn} with friends and earn rewards",
  "didntReceiveCode": "Didn’t receive the code?",
  "OnBoardingTitle1": "Stay Updated with Your Favorite Brews",
  "OnBoardingDescription1": "Get notified on the latest brews and exclusive cafe offers tailored for you.",
  "OnBoardingTitle2": "Embark on a Journey of Flavor in Every Cup",
  "OnBoardingDescription2": "Dive deeper into the world of coffee with curated selections and tasting notes.",
  "OnBoardingTitle3": "Craft Your Personalized Coffee Wishlist",
  "OnBoardingDescription3": "Build a collection of your favourite cafes so your perfect coffee moments are always close.",
  "topUpSuccessful": "Top-Up Successful",
  "topUpSuccessfulSubText": "Enjoy every sip with extra value",
  "copiedToClipboard": "Copied to clipboard",
  "pickUpFrom": "Pick Up From Branch",
  "noBranchSelected": "No Branch Selected",
  "select": "Select",
  "change": "Change",
  "notAvailable": "Not Available",
  "confirmRemoveItemName": "Are you sure you want to delete @item from the cart?",
  "showOptions": "Price per selection",
  "topUp": "Top Up",
  "permissionNotAllowed": "Location permission not allowed",
  "locationPermissionShouldAllowed": "Have you given the app permission to access the location in all time?",
  "openAppSettings": "Open app settings",
  "redeemYourPoints": "Redeem Your Points",
};
